// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHSE_Backend.Data.EF_Core;

#nullable disable

namespace MyHSE_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231101074958_LK01Header")]
    partial class LK01Header
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Docs.Documents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CHANGEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CHANGEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CONTENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOCID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILEPATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILESIZE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILETYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Docs.ObjectStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SYST")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ObjectStatus");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Docs.WorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ATIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUSER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUSERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUSER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUSERNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEQUENCE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFAPPR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFSTATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowLog");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.LK01.LK01Header", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FYear")
                        .HasColumnType("int");

                    b.Property<int?>("IncCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("IncClassificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IncDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("IncTime")
                        .HasColumnType("time");

                    b.Property<string>("IncidentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SumAfterInc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SumBeforeInc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SumDuringInc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LK01Headers");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Profile.ProfileSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CHANGEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CHANGEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPLOGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLOGO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PTITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMEZONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEBSITE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProfileSettings");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Profile.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AFCMKEY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CAPTCHA")
                        .HasColumnType("bit");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CHANGEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CHANGEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("GFCMKEY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LGCOUNT")
                        .HasColumnType("int");

                    b.Property<string>("LGDOMAIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LGOTP")
                        .HasColumnType("bit");

                    b.Property<int>("PWLENGTH")
                        .HasColumnType("int");

                    b.Property<bool>("PWNUMBER")
                        .HasColumnType("bit");

                    b.Property<bool>("PWSPCHAR")
                        .HasColumnType("bit");

                    b.Property<bool>("PWUPPERCASE")
                        .HasColumnType("bit");

                    b.Property<string>("SAPPW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPUSER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMSAPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSOURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TIMEOUT")
                        .HasColumnType("int");

                    b.Property<string>("WHATSAPPAPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Security");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.BusinessModules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("BUSMTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessModules");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.BusinessObjects", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("BUSMTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BusinessObjects");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.Classification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHARID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHARNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CLASSNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VALUE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.IncidentCategory", b =>
                {
                    b.Property<Guid>("IncCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IncCategoryId");

                    b.ToTable("IncidentCategories");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.IncidentClassification", b =>
                {
                    b.Property<Guid>("IncClassificId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncClassificDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncClassificName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("IncClassificId");

                    b.ToTable("IncidentClassifications");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.LK01Victim", b =>
                {
                    b.Property<Guid>("VictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FYear")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoSickLeaves")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VictCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("VictContractor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VictEmpNo")
                        .HasColumnType("int");

                    b.Property<string>("VictName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VictId");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.Organizations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURRENCY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LANG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ORGID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.Partners", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BPARFUNCT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUILDING")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTODIAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILADDR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FLOOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOUSE_NUM1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOUSE_NUM2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LANDMARK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBNUMBER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARFUNC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARNRID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELNUMBER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR01")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR02")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR03")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR04")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USR05")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIPCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.Plants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOUSENUM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORGID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLANT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STREET")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIPCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.PurchasingGroups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDGRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchasingGroups");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.PurchasingOrganizations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORGID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDORG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PurchasingOrganizations");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.RequestComments", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BusMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusObjType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CommentCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FYear")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.Units", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOMID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.Settings.VictimCategory", b =>
                {
                    b.Property<Guid>("VictCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VictCategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VictCategoryId");

                    b.ToTable("VictimCategories");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("BUSFTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSMTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BUSOBJTYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CHANGEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CHANGEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("ROLEID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDDATE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.UserGroups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ACTIVE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CREATEDBY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MODIFIEDBY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MODIFIEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("USGRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.UserRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CHANGEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CHANGEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CHANGEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CREATEDTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ROLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ROLEID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VALIDFROM")
                        .HasColumnType("datetime2");

                    b.Property<string>("VALIDTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("APPLOGS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUTHORITIES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AVALUE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CHKAPPVERSION")
                        .HasColumnType("bit");

                    b.Property<bool>("CHKDEVICEID")
                        .HasColumnType("bit");

                    b.Property<string>("COUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATFM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DCPFM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPARTMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESIGNATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICEID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICEPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICESNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICETYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIVISION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXTERNAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LANGUAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MODIFIEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("ORGID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARVW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGROUP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLANT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPLANT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGISTER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELMB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMEFM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMEZONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOKENID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USGRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USTYP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WKCTR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.WorkFlow.WFApprX", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusObjType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MEditMode")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("NEditMode")
                        .HasColumnType("bit");

                    b.Property<bool?>("REditMode")
                        .HasColumnType("bit");

                    b.Property<string>("WFLvlName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFSequence")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WFApprXs");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.WorkFlow.WFApprover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BusMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusObjType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EditMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kostl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFLvlName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WFSequence")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WFApprovers");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.WorkFlow.WFContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BusMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusObjType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FSequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WFContents");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.WorkFlow.WFGeneral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusMType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusObjType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Inbox")
                        .HasColumnType("bit");

                    b.Property<string>("Kostl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Outlook")
                        .HasColumnType("bit");

                    b.Property<string>("Plant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WFEsct")
                        .HasColumnType("bit");

                    b.Property<string>("WFPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WFRemd")
                        .HasColumnType("bit");

                    b.Property<string>("WFSequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("WFTRmd")
                        .HasColumnType("real");

                    b.Property<float?>("WFTSla")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("WFGenerals");
                });
#pragma warning restore 612, 618
        }
    }
}
