// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyHSE_Backend.Data.EF_Core;

#nullable disable

namespace MyHSE_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231023172539_reset")]
    partial class reset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("APPLOGS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AUTHORITIES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AVALUE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANGEDTIME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHKDEVICEID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATEDON")
                        .HasColumnType("datetime2");

                    b.Property<string>("DATFM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DCPFM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEPARTMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESIGNATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICEID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICEPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICESNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVICETYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIVISION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAILID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXTERNAL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GRADE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LANGUAGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIEDON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORGID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PARVW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PGROUP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLANT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPLANT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGISTER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELMB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELNR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMEFM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIMEZONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOKENID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UDID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USGRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USTYP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WKCTR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MyHSE_Backend.Data.DbModels.User.userGroups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ACTIVE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEDON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIEDBY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MODIFIEDON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USGRP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("userGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
